after_success:
- coveralls
deploy:
  true:
    branch: master
  distributions: sdist bdist_wheel
  user: mandeepb
  provider: pypi
  password:
    secure: "oxTYla2fHNRRjD0akv1eCpMbwpUILDTpn4iFnoaDi9z/CrFO2+AQKf4/WTQPPMfKYpYLzdaXBXV0r0amKIUm5fOGM4Pip3T4enTBAiBqjL8ykRsLaFpKuGGupHEy6OOPH6UQm4XxewbYCsGdRDWm6MX0VhNc5Wm0tuNZE/Ex1A4idstZpFse599AfL9Xsc6L9sUiaMnbcoZD8XcTnbOfXiE2BXPzCzjT40EGoa+NSEpvJKVsdfgLv/ihIvxsuwrH7/ns5wN0D2zIUmDo7EGWVO3GNVMmrAJ9Oz96kzCmY0GpnnEA3HPYdVIpzD0i49rEzVmPcXFbtLMsa+zyIonjH3LORS+tDoMPOCgX9fbG9CfxN1UOZGF/whte/f2VUyUKS4E7092/qFj5AY1Bl/2vgu+tDIyTu0iXHBlfShkka3exuSsRaG+GSgGV5NvdZ2C/QSgbwhYQCLKDu5q//JVDt+WX89m1flth06OECuC69Q9gMc/4AJO8jK++lhRIKB2gGODL5EFOIN0tAqwoP+r9gm8Qy0DaLbkYiD0y4g/HanwLQYn0FZ9Dv/TSRfIhVnx0NKbWedDnTWFnx/ClGHG1YWwZOk7xhNu2bPNFs6taycPhD+zYUBra+Hcco5qp0BLayYzhbEPfKVdw/KRmsyn19aD5LPhjW2wEFXM+701kAOg="
dist: trusty
install:
- pip install cryptography
- pip install coveralls
- python setup.py install
- pip install coverage
- pip install pytest
- pip install pytest-cov
language: python
notifications:
  email: false
python:
- '3.4'
- '3.5'
- '3.6'
script:
- py.test -s -v --cov=.
sudo: required
